/**
 * @file radiobutton.c
 *
 * @author Dalian University of Technology
 *
 * @section LICENSE
 *
 * Copyright (C) 2010 Dalian University of Technology
 *
 * This file is part of EDUGUI.
 *
 * EDUGUI is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * EDUGUI is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with EDUGUI; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301, USA.
 *
 * All rights reserved.
 **/

# include <stdio.h>
# include <stdlib.h>
# include <string.h>

# include <base_type.h>
# include <config_parser.h>
# include <log.h>
# include <comm.h>
# include <client_lib.h>
# include <graph.h>
# include <data_structures.h>
# include "compiler.h"

# include "radiobutton.h"

# define TMP_ARRAY_SIZE 256

/* The object generated by this file will be linked into user executable
 * with libwidget.so, so every user process will have a private copy of
 * this hashmap, which is exactly what we expect. */
static struct hashmap *hm_groups = NULL;

static si_t min(si_t x, si_t y)
{
    return x<y?x:y;
}

/* 按钮样式全局对象 */
static struct radiobutton_style radiobutton_default_style =
{
    {
        /* 初始化，默认未访问 */
        0,  /* .flag */

        /* 默认工作区域 */
        0,  /* .area_x */
        0,  /* .area_y */
        13,  /* .area_width */
        13,  /* .area_height */

        /* 默认边界宽度 */
        1,  /* .border_size */

        /* 默认宽度&高度 */
        13,  /* .maximum_width */
        13,  /* .minimum_width */
        13,  /* .maximum_height */
        13,  /* .minimum_height */

        /* 默认鼠标形状 */
        CURSOR_SHAPE_X, /* .cursor */

        /* 默认背景色 */
        255,    /* .back_color_r */
        255,    /* .back_color_g */
        255,  /* .back_color_b */
        0,  /* .back_color_a */

        /* 默认前景色 */
        0,  /* .fore_color_r */
        0,  /* .fore_color_g */
        0,  /* .fore_color_b */
        0,  /* .fore_color_a */
    }
};

/**
 * @brief 用radiobutton全局样式对象初始化radiobutton对象
 *
 * @param style radiobutton样式对象指针
 * @param b radiobutton指针
 *
 * @return 成功返回0，否则返回-1
 **/
static si_t radiobutton_init_with_default_style(struct radiobutton * b)
{
    char *config_path = get_config_path("radiobutton.cfg");

    si_t res = widget_init_with_default_style(config_path,
            WIDGET_POINTER(b), &radiobutton_default_style.common,
            NULL, 0);
    free(config_path);

    return res;
}

static si_t radiobutton_default_widget_show(struct radiobutton * b, union message * msg) 
{
    struct rectangle area;
    NOT_USED(msg);

    widget_absolute_area(WIDGET_POINTER(b), &area);

    /* 设置区域 */
    set_area(b->gd, area.x, area.y, area.width, area.height);

    /* 更新 */
    update(b->gd);

    return 0;
}

static void _paint_radiobutton(struct radiobutton* c, si_t is_selected, struct rectangle* area, int x, int y)
{
    struct widget *p =
        WIDGET_POINTER(object_parent(OBJECT_POINTER(c)));
    /* 外围背景色 */
    set_color(p->gd, p->back_color.r, p->back_color.g, p->back_color.b, p->back_color.a);
    fill_rectangle(c->gd, area->x, area->y, area->width, area->height);
    /* 背景色 */
    set_color(c->gd, c->back_color.r, c->back_color.g, c->back_color.b, c->back_color.a);
    fill_circle(c->gd,
            x + c->area.width/2,
            y + c->area.height/2,
            min(c->area.width, c->area.height)/2);

    /* 前景色 */
    set_color(c->gd, c->fore_color.r, c->fore_color.g, c->fore_color.b, c->fore_color.a);
    draw_circle(c->gd,
            x + c->area.width/2,
            y + c->area.height/2,
            min(c->area.width, c->area.height)/2);

    if(is_selected) {
        fill_circle(c->gd,
                    x + c->area.width/2,
                    y + c->area.height/2,
                    min(c->area.width, c->area.height)/4);
    }
}

static si_t radiobutton_default_widget_repaint(struct radiobutton *c, union message *msg)
{
    struct rectangle area;
    si_t x, y;
    NOT_USED(msg);

    /* 获得左上角的绝对坐标 */
    widget_absolute_coordinate(WIDGET_POINTER(c), &x, &y);
    /* 获得绝对的工作区域 */
    /* 将会舍弃不在父控件内的部分*/
    widget_absolute_area(WIDGET_POINTER(c), &area);
    /* 设置区域 */
    set_area(c->gd, area.x, area.y, area.width, area.height);

    _paint_radiobutton(c, c->selected, &area, x, y);
    return 0;
}

si_t radiobutton_default_callback(addr_t self, addr_t msg)
{
    struct radiobutton * b = self;
    union message * m = msg;

    widget_default_callback(b, m);

    switch(m->base.type)
    {
        case MESSAGE_TYPE_WIDGET_REPAINT:
            radiobutton_default_widget_repaint(b, m);
            radiobutton_default_widget_show(b, m);
            break;
        case MESSAGE_TYPE_WIDGET_SHOW:
            radiobutton_default_widget_show(b, m);
            break;
        case MESSAGE_TYPE_MOUSE_SINGLE_CLICK:
            radiobutton_select(b, m);
            if(b->click_callback) {
                b->click_callback(b->group_name, b->user_data);
            }
            break;
        default:
            break;
    }
    return 0;
}

void radiobutton_repaint(struct radiobutton* c)
{
    widget_repaint(WIDGET_POINTER(c));
}

void radiobutton_show(struct radiobutton* c)
{
    widget_show(WIDGET_POINTER(c));
}

static si_t radiobutton_hashmap_insert(const struct radiobutton *r)
{
    struct list *res = NULL;
    int retval = 0;
    if((res=hashmap_find(hm_groups,
                hashmap_key_generate(
                    r->group_name,
                    strlen(r->group_name)),
                1))) {
        retval = list_push_back(res, &r, sizeof(struct radiobutton *));
            /* always return 0 */
    } else {
        res = calloc(1, sizeof(struct list));
        if(!res || list_init(res)) {
            return -1;
        }
        if(-1 == list_push_back(res, &r, sizeof(struct radiobutton *))) {
            return -1;
        }
        retval =
            hashmap_insert(hm_groups,
                hashmap_pair_generate(
                    r->group_name,
                    strlen(r->group_name),
                    res));
    }
    return retval;
}

static const_addr_t radiobutton_list_match_pattern = NULL;
static size_t radiobutton_list_match_pattern_size = 0;

static si_t radiobutton_list_match(addr_t data)
{
    if(!radiobutton_list_match_pattern && !data) {
        return 1;
    }
    if(!radiobutton_list_match_pattern || !data) {
        radiobutton_list_match_pattern = NULL;
        return 0;
    }
    if(!memcmp(data, radiobutton_list_match_pattern,
                radiobutton_list_match_pattern_size)) {
        radiobutton_list_match_pattern = NULL;
        return 1;
    } else {
        radiobutton_list_match_pattern = NULL;
        return 0;
    }
}

static si_t radiobutton_list_find_focus(addr_t data)
{
    if(!data) return 0;
    return (*(struct radiobutton **)data)->selected;
}

static void radiobutton_hashmap_erase(const struct radiobutton *r)
{
    struct list *res = NULL;
    struct hashmap_key *key =
        hashmap_key_generate(r->group_name, strlen(r->group_name));
    if((res=hashmap_find(hm_groups, key, 0))) {
        struct list_node *posi;
        radiobutton_list_match_pattern = r;
        radiobutton_list_match_pattern_size =
            sizeof(const struct radiobutton *);
        posi = list_find(res, radiobutton_list_match);
        if(posi)
            list_erase(res, posi);
        if(list_size(res)<=0) {
            hashmap_erase(hm_groups, key, 0);
        }
    }
    free(key);
}

struct radiobutton* radiobutton_init(const char *group_name, int selected)
{
    struct radiobutton * addr;

    /* 分配存储空间 */
    addr = (struct radiobutton *)malloc(sizeof(struct radiobutton));
    if(addr == NULL) {
        EGUI_PRINT_SYS_ERROR("fail to malloc");
        return NULL;
    }

    if(!(addr=widget_init_common(WIDGET_POINTER(addr), 0))) {
        return NULL;
    }

    if(!hm_groups) {
        hm_groups = hashmap_init();
    }

    addr->name = "struct radiobutton";

    /* 用全局样式对象初始化radiobutton样式 */
    radiobutton_init_with_default_style(addr);

    addr->callback = radiobutton_default_callback;
    addr->group_name = group_name;
    addr->click_callback = NULL;
    addr->user_data = NULL;

    if(-1 == radiobutton_hashmap_insert(addr)) {
        radiobutton_exit(addr);
        return NULL;
    }

    if(selected) {
        addr->selected = 1;
    } else {
        addr->selected = 0;
    }

    return addr;
}

/*
   一般用户并不需要调用这个
   用户应用程序退出之后，application 会释放这个控件所占的空间。
   而窗口管理程序会释放所有资源，包括申请的每个图形设备。
   */
si_t radiobutton_exit(struct radiobutton * c)
{
    radiobutton_hashmap_erase(c);
    return widget_exit(WIDGET_POINTER(c));
}

void radiobutton_set_bounds(struct radiobutton *c, si_t x, si_t y, si_t width , si_t height)
{
    widget_set_bounds(WIDGET_POINTER(c), x, y, width, height);
}

void radiobutton_set_color(struct radiobutton *c, struct color *fcolor, struct color *bcolor)
{
    widget_set_color(WIDGET_POINTER(c), fcolor, bcolor);
}

static void radiobutton_force_state(struct radiobutton *c, si_t selected)
{
    c->selected = selected;
}

void radiobutton_select(struct radiobutton* c, union message *m)
{
    struct hashmap_key *key =
        hashmap_key_generate(c->group_name, strlen(c->group_name));
    struct list *res = NULL;
    if((res=hashmap_find(hm_groups, key, 0))) {
        struct list_node *data;
        data = list_find(res, radiobutton_list_find_focus);
        if(data) {
            struct radiobutton *focus;
            focus = *(struct radiobutton **)data->data;
            radiobutton_force_state(focus, 0);
            radiobutton_default_widget_repaint(focus, m);
            radiobutton_default_widget_show(focus, m);
        }
        radiobutton_force_state(c, 1);
        radiobutton_default_widget_repaint(c, m);
        radiobutton_default_widget_show(c, m);
    }
    free(key);
}
